# Generated by Django 5.1.2 on 2024-11-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('fijo', 'Fijo')], default='movil', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.telefono')),
            ],
        ),
    ]
