# Generated by Django 5.1.1 on 2024-11-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=50, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=50, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre'),
        ),
    ]
